### ISSUE TITLE
Add 'Noise' setting/control to Monitor Simulation Controls

### ISSUE THREAD

**Issue by oh-ren** [openMSX/wxcatapult#38]
See subject :)

While I'm at it: `brightness` & `contrast` could be added as well? + perhaps the `deflicker` option? (Am I missing more useful settings/toggles here?)

**Comment by MBilderbeek** [comment]
OK, I already created a patch for this, but it's too late for the new release now.

**Comment by oh-ren** [comment]
That's cool.. (Using dev. builds anyway :))

Since I know your plans of moving to an openMSX with full GUI (right?) I wonder if you still consider Catapult as being under 'active development'?
Speaking for myself: I don't think I'm really missing a GUI. In a way I like how it is. (Of course there is (still (ample)) room for improvement.)

**Comment by MBilderbeek** [comment]
As the readme of Catapult says, it's officially dead since about 2007. But when it's not too much work, I tweak it a bit here and there. But do not expect major work on it, it's really dead.

I never use it myself by the way...

**Comment by oh-ren** [comment]
> As the readme of Catapult says, it's officially dead

I should pay better attention (actually **read** stuff perhaps)..  ;-)

> I never use it myself by the way...

Well, I do find it convenient to click & drag every now & then, in conjunction with using the console.. :)

EDIT: perhaps I should also acquaint myself some more with the OSD menu, I tend to forget it's there.. ;) I see there I do find the `Noise` setting inside `Video Settings`. Though some other things that are present in Catapul's Video Controls tab are not present in the OSD menu (e.g. 'Deinterlace').
